# Generated by Django 5.0.4 on 2024-04-26 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='participant',
        ),
        migrations.AddField(
            model_name='function',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ministry'),
        ),
        migrations.AddField(
            model_name='scale',
            name='ministry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.ministry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ministry'),
        ),
    ]
