# Generated by Django 5.0.4 on 2024-11-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ministry_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='function',
        ),
    ]
