# Generated by Django 5.0.4 on 2024-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_of_birth_user_birth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='function',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='song',
        ),
        migrations.RemoveField(
            model_name='user',
            name='function',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ministry',
        ),
        migrations.AddField(
            model_name='scale',
            name='function',
            field=models.ManyToManyField(blank=True, null=True, to='app.function'),
        ),
        migrations.AddField(
            model_name='scale',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='app.user'),
        ),
        migrations.AddField(
            model_name='scale',
            name='song',
            field=models.ManyToManyField(blank=True, null=True, to='app.song'),
        ),
        migrations.AddField(
            model_name='user',
            name='function',
            field=models.ManyToManyField(blank=True, null=True, to='app.function'),
        ),
        migrations.AddField(
            model_name='user',
            name='ministry',
            field=models.ManyToManyField(blank=True, null=True, to='app.ministry'),
        ),
    ]
