# Generated by Django 5.0.4 on 2024-05-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_scale_function_remove_scale_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ministry'),
        ),
    ]
