# Generated by Django 5.0.4 on 2025-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
